name: Release PyPi pkgs

on:
  workflow_dispatch:

jobs:
  publish-core:
    name: Build & publish pepedd (core)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build core
        run: uv build --package pepedd

      - name: Publish core
        run: uv publish --package pepedd -t ${{ secrets.PYPI_TOKEN }}


  publish-nodes:
    name: Build & publish pepedd_nodes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build nodes
        run: uv build --package pepedd_nodes

      - name: Publish nodes
        run: uv publish --package pepedd_nodes -t ${{ secrets.PYPI_TOKEN }}
